import { StyleSheet } from "react-native";

export const categoryStyles = StyleSheet.create({
  fullContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
  },
  categorySelector: {
    padding: 8,
  },
  filterBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  filterOption: {
    flexDirection: "row",
    alignItems: "center",
  },
  filterText: {
    marginHorizontal: 4,
    fontSize: 14,
  },
  productGrid: {
    padding: 8,
  },
  row: {
    justifyContent: "space-between",
    marginBottom: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#666',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
    marginTop: 16,
  },
  productCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  productImageContainer: {
    position: "relative",
    alignItems: "center",
    marginBottom: 8,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#f9f9f9",
  },
  productImage: {
    width: "100%",
    height: 150,
    resizeMode: "cover",
  },
  badgeContainer: {
    position: "absolute",
    top: 8,
    right: 8,
  },
  badge: {
    backgroundColor: "#ff6b81",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  productTitle: {
    fontSize: 14,
    fontWeight: "500",
    color: "#888",
  },
  productDescription: {
    fontSize: 13,
    color: "#333",
    marginVertical: 4,
    height: 36,
    fontWeight: "500",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 4,
  },
  ratingText: {
    fontSize: 12,
    color: "#666",
    marginLeft: 4,
  },
  price: {
    fontSize: 15,
    fontWeight: "bold",
    marginTop: 4,
    color: "#ff6b81",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  modalBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  sortModal: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    paddingBottom: 32,
  },
  sortModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 16,
    textAlign: "center",
  },
  sortOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  selectedSortOption: {
    backgroundColor: "#fff2f4",
  },
  sortOptionText: {
    fontSize: 16,
    color: "#333",
  },
  selectedSortOptionText: {
    color: "#ff6b81",
    fontWeight: "500",
  },
  categoryModal: {
    position: "absolute",
    top: '20%',
    left: 20,
    right: 20,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    paddingBottom: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 16,
    textAlign: "center",
  },
  categoryOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  categoryOptionContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  selectedCategoryOption: {
    backgroundColor: "#fff2f4",
  },
  categoryOptionText: {
    fontSize: 16,
    color: "#333",
    marginLeft: 12,
  },
  selectedCategoryOptionText: {
    color: "#ff6b81",
    fontWeight: "500",
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#666',
    marginTop: 16,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: '#ff6b81',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: '500',
  },
  modalLoadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  modalErrorContainer: {
    padding: 20,
    alignItems: 'center',
  },
  filterModal: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%', // Limit height to 80% of the screen
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  filterModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  filterModalTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  filterScrollView: {
    padding: 16,
    maxHeight: '70%', // Ensure there's space for buttons
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 12,
    color: '#333',
  },
  loadingIndicator: {
    marginVertical: 10,
  },
  brandList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  brandOption: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 20, // More rounded for multi-select appearance
    marginRight: 8,
    marginBottom: 8,
  },
  selectedBrandOption: {
    backgroundColor: '#ff6b81',
    borderColor: '#ff6b81',
  },
  brandOptionText: {
    fontSize: 14,
    color: '#333',
  },
  selectedBrandOptionText: {
    color: 'white',
    fontWeight: '500',
  },
  priceRangeList: {
    marginBottom: 20,
  },
  priceRangeOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    marginBottom: 8,
  },
  selectedPriceRangeOption: {
    backgroundColor: '#ff6b81',
    borderColor: '#ff6b81',
  },
  priceRangeText: {
    fontSize: 14,
    color: '#333',
  },
  selectedPriceRangeText: {
    color: 'white',
    fontWeight: '500',
  },
  filterActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  resetButton: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingVertical: 12,
    borderRadius: 8,
    marginRight: 8,
    alignItems: 'center',
  },
  resetButtonText: {
    color: '#333',
    fontWeight: '500',
    fontSize: 16,
  },
  applyButton: {
    flex: 1,
    backgroundColor: '#ff6b81',
    paddingVertical: 12,
    borderRadius: 8,
    marginLeft: 8,
    alignItems: 'center',
  },
  applyButtonText: {
    color: 'white',
    fontWeight: '500',
    fontSize: 16,
  },
  resetFiltersButton: {
    marginTop: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  resetFiltersText: {
    color: '#ff6b81',
    fontWeight: '500',
  },
  errorSubText: {
    fontSize: 12,
    color: '#ff6b81',
    marginTop: 4,
  },
  notFoundText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginVertical: 16,
  },
  filterActiveIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff6b81',
    marginLeft: 4,
  },
});
